[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F103RB"
[build]
#target = "thumbv7em-none-eabihf"
target = "thumbv7m-none-eabi"

[env]
DEFMT_LOG = "trace"
